import Link from "next/link";
import { ArrowUpRight, ArrowRight, Check, ShieldCheck, FolderLock, MessagesSquare, Building2, BriefcaseBusiness, Handshake, MapPin, MoveUpRight } from "lucide-react";
import { Brand } from "@/components/brand";
export default function Home(){return <>
  <header className="marketing-header"><div className="marketing-nav"><Brand/><nav aria-label="Main navigation"><a href="#platform">The platform</a><a href="#for-you">Who it’s for</a><a href="#process">How it works</a></nav><div className="nav-actions"><Link className="text-link" href="/login">Sign in</Link><Link className="button button-dark" href="/register">Get started <ArrowUpRight size={16}/></Link></div></div></header>
  <main>
    <section className="hero"><div className="hero-inner"><div className="hero-copy"><p className="eyebrow"><span className="tiny-maple">✳</span> BUILT FOR CANADIAN BUSINESS</p><h1>Great businesses.<br/>New beginnings.</h1><p className="hero-description">Find the right opportunity. Bring the right people together. A private workspace for the next chapter of Canadian business.</p><div className="hero-actions"><Link href="/register" className="button button-green">Find your next chapter <ArrowRight size={18}/></Link><Link href="/login" className="button button-quiet">Explore the demo <ArrowUpRight size={17}/></Link></div><div className="hero-proof"><ShieldCheck size={18}/><span>Confidential by design</span><span className="divider-dot">·</span><span>From introduction to diligence</span></div></div>
      <div className="hero-product" aria-label="Illustrative Acquire deal workspace"><div className="mock-header"><span className="mock-mark">A</span><span>Your next opportunity</span><span className="badge badge-green">CANADA</span></div><div className="mock-deal"><div className="flex items-center justify-between"><span className="icon-tile"><Building2 size={22}/></span><span className="badge">Business services</span></div><p className="eyebrow mt-6">CONFIDENTIAL OPPORTUNITY</p><h2>Project Cedar</h2><p className="muted flex items-center gap-1"><MapPin size={14}/> Ontario, Canada</p><div className="mock-metrics"><div><span>Annual revenue</span><strong>C$8.4M</strong></div><div><span>EBITDA</span><strong>C$1.8M</strong></div><div><span>Stage</span><strong>Due diligence</strong></div></div></div><div className="mock-progress"><span className="check-icon"><Check size={15}/></span><div><strong>The right people. In one place.</strong><span>Deal team connected · Documents organized</span></div><FolderLock size={21}/></div><p className="mock-caption">Illustrative transaction · Fictional company data</p></div>
    </div><div className="hero-bottom"><span>ONE SHARED WORKSPACE</span><span>Business owners</span><span>Acquisition buyers</span><span>M&A advisors</span><span className="canada-tag">Coast to coast <MoveUpRight size={16}/></span></div></section>
    <section id="platform" className="marketing-section"><div className="section-heading"><div><p className="eyebrow">LESS FRICTION. MORE FORWARD.</p><h2>Keep the deal moving.<br/>Keep everyone aligned.</h2></div><p>Business acquisitions have enough moving parts. Give your team one place to connect, share information, and take the next step.</p></div><div className="feature-grid">{[{Icon:Handshake,title:"Make the right connection",text:"Share your acquisition criteria or a confidential business teaser. Focus conversations on opportunities that fit."},{Icon:FolderLock,title:"Share with confidence",text:"Keep documents organized by deal. Review NDAs and control each buyer’s access to confidential information."},{Icon:MessagesSquare,title:"Move forward together",text:"Bring conversations, indicative offers, diligence requests, and deadlines into a shared transaction workspace."}].map(({Icon,title,text},i)=><article className="feature" key={title}><span className="feature-number">0{i+1}</span><Icon size={28} strokeWidth={1.5}/><h3>{title}</h3><p>{text}</p></article>)}</div></section>
    <section id="for-you" className="audiences"><div className="marketing-section"><p className="eyebrow">YOUR ROLE. YOUR WORKSPACE.</p><h2>A better process on every side.</h2><div className="audience-grid">{[{role:"buyer",Icon:BriefcaseBusiness,title:"For buyers",text:"Build a focused pipeline. Review relevant Canadian businesses, request information, and manage diligence with your deal team.",cta:"Find your next acquisition"},{role:"owner",Icon:Building2,title:"For business owners",text:"Prepare for what comes next. Choose your advisor, control what you share, and keep a clear view of buyer interest and offers.",cta:"Plan your next chapter"},{role:"advisor",Icon:Handshake,title:"For M&A advisors",text:"Give every mandate a home. Coordinate buyers, organize documents, and keep your clients informed across the entire process.",cta:"Bring your deal team together"}].map(({role,Icon,title,text,cta})=><article key={role}><Icon size={25}/><h3>{title}</h3><p>{text}</p><Link href={`/register?role=${role}`}>{cta}<ArrowUpRight size={17}/></Link></article>)}</div></div></section>
    <section id="process" className="marketing-section"><div className="section-heading"><div><p className="eyebrow">FROM FIRST HELLO TO WHAT’S NEXT</p><h2>A clear path through the process.</h2></div><p>Designed for established Canadian businesses with C$1M–C$20M in annual revenue, and the people helping them change hands.</p></div><ol className="process-grid">{[["Connect","Create your profile, define your criteria, and start a relevant conversation."],["Qualify","Review interest, exchange NDAs, and approve access on your terms."],["Collaborate","Share documents, discuss offers, and work through diligence together."],["Progress","Keep milestones visible as your team works toward closing."]].map(([title,text],i)=><li key={title}><span>0{i+1}</span><h3>{title}</h3><p>{text}</p></li>)}</ol></section>
    <section className="closing-cta"><p className="eyebrow">THE NEXT CHAPTER IS YOURS</p><h2>Let’s make the introduction.</h2><p>Start your workspace, or explore all three roles with fictional demo data.</p><Link className="button button-white" href="/register">Create your account <ArrowUpRight size={18}/></Link><Link className="cta-demo" href="/login">Explore the demo</Link></section>
  </main><footer className="marketing-footer"><Brand/><p>Connecting the next chapter of Canadian business.</p><div><Link href="/about-this-release">About this release</Link><span>© {new Date().getFullYear()} Acquire</span></div></footer>
</>;}
