"use client";
import { useState } from "react";
import Link from "next/link";
import { ArrowRight, Building2, BriefcaseBusiness, Handshake, LoaderCircle } from "lucide-react";
import { Brand } from "./brand";
import type { Role } from "@/lib/types";
export function AuthForm({mode,demo,initialRole="buyer",registration=true}:{mode:"login"|"register";demo:boolean;initialRole?:Role;registration?:boolean}){
  const [busy,setBusy]=useState(false),[error,setError]=useState("");
  async function submit(body:Record<string,unknown>){setBusy(true);setError("");try{const res=await fetch("/api/auth",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});const json=await res.json();if(!res.ok)throw new Error(json.error);window.location.assign("/app");}catch(e){setError(e instanceof Error?e.message:"Unable to sign in.");setBusy(false);}}
  return <main className="auth-page"><aside className="auth-aside"><Brand dark/><div><p className="eyebrow">YOUR NEXT CHAPTER</p><h1>Good businesses<br/>deserve a<br/><em>great future.</em></h1><p>A shared workspace for the people making Canadian business transitions happen.</p></div><span className="auth-aside-footer">Private connections. Meaningful progress.</span></aside><section className="auth-main"><Link href="/" className="auth-back">← Back to Succera</Link><div className="auth-card"><p className="eyebrow">SUCCERA WORKSPACE</p><h2>{mode==="login"?"Welcome back.":"Start your next chapter."}</h2><p className="muted">{mode==="login"?"Sign in to your deal workspace.":"One account. The right workspace for your role."}</p>{error&&<div className="form-error" role="alert">{error}</div>}
    {mode==="register"&&!registration?<p className="notice">Registration is currently closed. Contact your pilot administrator.</p>:<form className="stack-form" onSubmit={e=>{e.preventDefault();void submit({action:mode,...Object.fromEntries(new FormData(e.currentTarget))});}}>
      {mode==="register"&&<><label>Full name<input name="name" autoComplete="name" required minLength={2} maxLength={100}/></label><label>Company<input name="company" autoComplete="organization" required minLength={2} maxLength={160}/></label><label>I’m joining as<select name="role" defaultValue={initialRole}><option value="buyer">An acquisition buyer</option><option value="owner">A business owner</option><option value="advisor">An M&A advisor</option></select></label></>}
      <label>Email address<input name="email" type="email" autoComplete="email" placeholder="you@company.ca" required maxLength={254}/></label><label>Password<input name="password" type="password" autoComplete={mode==="login"?"current-password":"new-password"} required minLength={mode==="register"?12:1} maxLength={128}/>{mode==="register"&&<span className="field-hint">Use at least 12 characters.</span>}</label><button disabled={busy} className="button button-green w-full">{busy?<LoaderCircle size={18}/>:mode==="login"?"Sign in":"Create account"}<ArrowRight size={17}/></button>
    </form>}
    <p className="auth-switch">{mode==="login"?"New to Succera? ":"Already have an account? "}<Link href={mode==="login"?"/register":"/login"}>{mode==="login"?"Create an account":"Sign in"}</Link></p>
    {demo&&<div className="demo-entry"><span>EXPLORE WITH FICTIONAL DATA</span><div>{([{role:"advisor",Icon:Handshake},{role:"buyer",Icon:BriefcaseBusiness},{role:"owner",Icon:Building2}] as const).map(({role,Icon})=><button key={role} disabled={busy} onClick={()=>void submit({action:"demo",role})}><Icon size={19}/><span>{role.charAt(0).toUpperCase()+role.slice(1)} demo</span></button>)}</div><p>Shared demo accounts. Don’t upload personal or confidential files.</p></div>}
    <p className="auth-release"><Link href="/about-this-release">Early-access release · Read what’s included</Link></p></div></section></main>;
}
